INFO 2025-03-14 16:36:14,250 autoreload 22056 12720 Watching for file changes with StatReloader
INFO 2025-03-14 16:37:26,867 autoreload 22144 20788 Watching for file changes with StatReloader
INFO 2025-03-14 16:37:35,742 basehttp 22144 3120 "GET / HTTP/1.1" 200 40
WARNING 2025-03-14 16:37:35,816 log 22144 3120 Not Found: /favicon.ico
WARNING 2025-03-14 16:37:35,817 basehttp 22144 3120 "GET /favicon.ico HTTP/1.1" 404 4513
INFO 2025-03-14 16:37:55,418 basehttp 22144 3120 "GET / HTTP/1.1" 200 40
INFO 2025-03-14 16:38:01,374 basehttp 22144 3120 "GET /admin HTTP/1.1" 301 0
INFO 2025-03-14 16:38:01,397 basehttp 22144 22140 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-03-14 16:38:01,549 basehttp 22144 22140 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
INFO 2025-03-14 16:38:01,706 basehttp 22144 22140 "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-14 16:38:01,718 basehttp 22144 14524 "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-03-14 16:38:01,720 basehttp 22144 8328 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-14 16:38:01,720 basehttp 22144 18628 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-14 16:38:01,721 basehttp 22144 20828 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-14 16:38:01,731 basehttp 22144 16844 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-14 16:38:01,743 basehttp 22144 20828 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-14 16:38:21,793 basehttp 22144 20828 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
INFO 2025-03-14 16:38:28,674 basehttp 22144 20828 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
INFO 2025-03-14 16:38:54,892 basehttp 22144 20828 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
INFO 2025-03-14 16:39:02,664 basehttp 22144 20828 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
INFO 2025-03-14 16:42:20,094 basehttp 22144 20828 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-03-14 16:42:20,143 basehttp 22144 20828 "GET /admin/ HTTP/1.1" 200 10301
INFO 2025-03-14 16:42:20,166 basehttp 22144 20828 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-03-14 16:42:20,179 basehttp 22144 16844 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-03-14 16:42:20,180 basehttp 22144 20828 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
ERROR 2025-03-14 16:42:48,734 log 22144 20828 Internal Server Error: /admin/inspection/cliinspector/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_cliinspector

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 1999, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_cliinspector
ERROR 2025-03-14 16:42:48,751 basehttp 22144 20828 "GET /admin/inspection/cliinspector/ HTTP/1.1" 500 203154
INFO 2025-03-14 16:43:10,667 basehttp 22144 20828 "GET /admin/auth/group/ HTTP/1.1" 200 10761
INFO 2025-03-14 16:43:10,693 basehttp 22144 20828 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-14 16:43:10,704 basehttp 22144 18616 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-14 16:43:10,712 basehttp 22144 16484 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-14 16:43:10,715 basehttp 22144 19976 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-14 16:43:10,715 basehttp 22144 13368 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-14 16:43:10,723 basehttp 22144 20828 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-14 16:43:10,727 basehttp 22144 18616 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-14 16:43:10,734 basehttp 22144 16484 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-14 16:43:10,743 basehttp 22144 16484 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-14 16:43:10,756 basehttp 22144 16844 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-14 16:43:10,777 basehttp 22144 16844 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-14 16:43:10,823 basehttp 22144 19976 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-14 16:43:10,849 basehttp 22144 19976 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-14 16:43:15,649 basehttp 22144 19976 "GET /admin/auth/user/ HTTP/1.1" 200 14368
INFO 2025-03-14 16:43:15,663 basehttp 22144 16844 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-14 16:43:15,670 basehttp 22144 19976 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-03-14 16:43:15,690 basehttp 22144 16844 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-14 16:43:15,692 basehttp 22144 19976 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
ERROR 2025-03-14 16:43:26,721 log 22144 19976 Internal Server Error: /admin/inspection/cliinspector/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_cliinspector

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 1999, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_cliinspector
ERROR 2025-03-14 16:43:26,737 basehttp 22144 19976 "GET /admin/inspection/cliinspector/ HTTP/1.1" 500 203164
INFO 2025-03-14 16:46:43,224 basehttp 22144 19976 "GET /admin/auth/user/ HTTP/1.1" 200 14368
INFO 2025-03-14 16:46:47,464 basehttp 22144 19976 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10859
INFO 2025-03-14 16:46:47,480 basehttp 22144 19976 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-14 16:46:50,690 basehttp 22144 19976 "GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 10677
ERROR 2025-03-14 16:46:52,540 log 22144 19976 Internal Server Error: /admin/inspection/supervisor/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_supervisor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 1999, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_supervisor
ERROR 2025-03-14 16:46:52,555 basehttp 22144 19976 "GET /admin/inspection/supervisor/ HTTP/1.1" 500 203053
INFO 2025-03-14 16:46:54,584 basehttp 22144 19976 "GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 10677
ERROR 2025-03-14 16:46:56,039 log 22144 19976 Internal Server Error: /admin/inspection/inspection/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_inspection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 1999, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_inspection
ERROR 2025-03-14 16:46:56,054 basehttp 22144 19976 "GET /admin/inspection/inspection/ HTTP/1.1" 500 203143
INFO 2025-03-15 10:58:41,962 autoreload 4120 10584 Watching for file changes with StatReloader
INFO 2025-03-15 11:12:17,349 autoreload 4120 10584 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\settings.py changed, reloading.
INFO 2025-03-15 11:12:19,380 autoreload 11372 4788 Watching for file changes with StatReloader
INFO 2025-03-15 11:12:22,569 autoreload 11372 4788 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 11:12:23,846 autoreload 8548 5484 Watching for file changes with StatReloader
INFO 2025-03-15 11:50:36,278 autoreload 8548 5484 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 11:50:37,415 autoreload 17296 10736 Watching for file changes with StatReloader
INFO 2025-03-15 11:52:44,787 autoreload 19924 11352 Watching for file changes with StatReloader
INFO 2025-03-15 12:41:34,493 autoreload 19924 11352 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 12:41:35,839 autoreload 19020 15924 Watching for file changes with StatReloader
INFO 2025-03-15 12:41:41,145 autoreload 19020 15924 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 12:41:42,377 autoreload 20292 11544 Watching for file changes with StatReloader
INFO 2025-03-15 12:43:10,211 autoreload 20292 11544 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 12:43:11,357 autoreload 5412 15816 Watching for file changes with StatReloader
INFO 2025-03-15 12:49:11,335 autoreload 5412 15816 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-03-15 12:49:12,555 autoreload 18856 12668 Watching for file changes with StatReloader
INFO 2025-03-15 12:50:35,752 autoreload 14936 12872 Watching for file changes with StatReloader
INFO 2025-03-15 12:50:54,047 basehttp 18856 5052 "GET / HTTP/1.1" 200 40
INFO 2025-03-15 12:51:01,511 basehttp 18856 5052 "GET /admin/ HTTP/1.1" 200 10301
INFO 2025-03-15 12:51:01,531 basehttp 18856 5052 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,540 basehttp 18856 5052 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,540 basehttp 18856 22288 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,542 basehttp 18856 20160 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,542 basehttp 18856 17268 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,543 basehttp 18856 17660 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,546 basehttp 18856 17660 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,552 basehttp 18856 17660 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-03-15 12:51:01,552 basehttp 18856 17268 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-03-15 12:51:19,225 basehttp 18856 17660 "GET / HTTP/1.1" 200 40
INFO 2025-03-15 12:51:23,003 basehttp 18856 17660 "GET /admin/ HTTP/1.1" 200 10301
INFO 2025-03-15 12:51:31,762 basehttp 18856 17660 "GET /admin/auth/user/ HTTP/1.1" 200 14368
INFO 2025-03-15 12:51:31,796 basehttp 18856 17660 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,805 basehttp 18856 22288 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,807 basehttp 18856 20160 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,809 basehttp 18856 5052 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,811 basehttp 18856 17660 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,813 basehttp 18856 9780 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,814 basehttp 18856 20160 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,815 basehttp 18856 5052 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,815 basehttp 18856 22288 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,817 basehttp 18856 17660 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,820 basehttp 18856 9780 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,824 basehttp 18856 9780 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,848 basehttp 18856 17268 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-15 12:51:31,867 basehttp 18856 17268 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-03-15 12:51:31,966 basehttp 18856 17660 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-15 12:51:31,969 basehttp 18856 9780 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-03-15 12:51:39,734 basehttp 18856 9780 "GET /admin/ HTTP/1.1" 200 10301
INFO 2025-03-15 14:52:44,516 autoreload 14936 12872 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\settings.py changed, reloading.
INFO 2025-03-15 14:52:44,524 autoreload 18856 12668 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\settings.py changed, reloading.
INFO 2025-03-15 14:52:46,478 autoreload 17464 2952 Watching for file changes with StatReloader
INFO 2025-03-15 14:52:46,478 autoreload 12644 19812 Watching for file changes with StatReloader
INFO 2025-03-15 15:34:12,317 autoreload 12644 19812 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:34:12,318 autoreload 17464 2952 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:34:14,633 autoreload 7504 8844 Watching for file changes with StatReloader
INFO 2025-03-15 15:34:14,633 autoreload 7872 19112 Watching for file changes with StatReloader
INFO 2025-03-15 15:34:59,364 autoreload 7872 19112 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:34:59,380 autoreload 7504 8844 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:35:00,378 autoreload 18540 17560 Watching for file changes with StatReloader
INFO 2025-03-15 15:35:00,388 autoreload 12700 6620 Watching for file changes with StatReloader
INFO 2025-03-15 15:35:07,554 autoreload 12700 6620 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:35:07,558 autoreload 18540 17560 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:35:08,502 autoreload 172 7952 Watching for file changes with StatReloader
r
INFO 2025-03-15 15:35:13,480 autoreload 20424 15048 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:35:13,488 autoreload 172 7952 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:35:14,393 autoreload 13964 15840 Watching for file changes with StatReloader
INFO 2025-03-15 15:35:14,394 autoreload 11900 15928 Watching for file changes with StatReloader
INFO 2025-03-15 15:35:21,475 autoreload 13964 15840 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:35:21,485 autoreload 11900 15928 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 15:35:22,334 autoreload 9516 10972 Watching for file changes with StatReloader
INFO 2025-03-15 15:35:22,334 autoreload 9224 9648 Watching for file changes with StatReloader
INFO 2025-03-15 16:01:05,555 autoreload 9516 10972 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 16:01:05,579 autoreload 9224 9648 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 16:01:06,722 autoreload 3396 21020 Watching for file changes with StatReloader
INFO 2025-03-15 16:01:06,723 autoreload 16016 1852 Watching for file changes with StatReloader
INFO 2025-03-15 16:08:31,060 autoreload 16016 1852 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 16:08:31,078 autoreload 3396 21020 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 16:08:31,958 autoreload 6292 440 Watching for file changes with StatReloader
INFO 2025-03-15 16:08:31,962 autoreload 10508 13404 Watching for file changes with StatReloader
INFO 2025-03-15 16:08:58,595 autoreload 10508 13404 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 16:08:58,605 autoreload 6292 440 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\urls.py changed, reloading.
INFO 2025-03-15 16:08:59,570 autoreload 7436 8752 Watching for file changes with StatReloader
INFO 2025-03-15 16:08:59,581 autoreload 9648 9224 Watching for file changes with StatReloader
INFO 2025-03-15 16:35:17,614 autoreload 1196 4076 Watching for file changes with StatReloader
INFO 2025-03-15 16:35:23,438 basehttp 7436 16772 "GET / HTTP/1.1" 200 40
INFO 2025-03-15 16:35:32,136 basehttp 7436 16772 "GET / HTTP/1.1" 200 40
INFO 2025-03-15 16:35:35,167 basehttp 7436 16772 "GET /admin/ HTTP/1.1" 200 10301
INFO 2025-03-15 16:35:49,626 basehttp 7436 16772 "GET /admin/auth/group/ HTTP/1.1" 200 10761
INFO 2025-03-15 16:35:49,657 basehttp 7436 16772 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-15 16:35:54,469 basehttp 7436 16772 "GET /admin/inspection/cliinspector/add/ HTTP/1.1" 200 12504
INFO 2025-03-15 16:35:54,487 basehttp 7436 21168 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-15 16:35:54,552 basehttp 7436 16772 "GET /static/admin/css/forms.css HTTP/1.1" 200 8794
INFO 2025-03-15 16:35:54,558 basehttp 7436 768 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-03-15 16:35:54,568 basehttp 7436 21168 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
INFO 2025-03-15 16:35:54,573 basehttp 7436 16772 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
ERROR 2025-03-15 16:35:56,941 log 7436 16772 Internal Server Error: /admin/inspection/fabricdefect/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_fabricdefect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 1999, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_fabricdefect
ERROR 2025-03-15 16:35:56,970 basehttp 7436 16772 "GET /admin/inspection/fabricdefect/ HTTP/1.1" 500 204250
INFO 2025-03-15 16:36:10,725 basehttp 7436 16772 "GET /admin/inspection/cliinspector/add/ HTTP/1.1" 200 12504
INFO 2025-03-15 17:02:19,109 basehttp 7436 15184 "GET / HTTP/1.1" 200 40
INFO 2025-03-15 17:02:27,208 basehttp 7436 15184 "GET /admin/ HTTP/1.1" 200 10301
WARNING 2025-03-15 17:05:43,884 log 7436 3112 Unauthorized: /api/login/
WARNING 2025-03-15 17:05:43,885 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 401 31
INFO 2025-03-15 17:07:29,508 basehttp 7436 20140 "GET /admin/auth/user/ HTTP/1.1" 200 14368
INFO 2025-03-15 17:07:29,533 basehttp 7436 20140 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-15 17:07:39,384 basehttp 7436 20140 "GET /admin/auth/user/?o= HTTP/1.1" 200 14278
INFO 2025-03-15 17:07:39,408 basehttp 7436 20140 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-15 17:07:53,399 basehttp 7436 20140 "GET /admin/password_change/ HTTP/1.1" 200 10454
WARNING 2025-03-15 17:09:41,713 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:09:41,714 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:06,867 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:06,867 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:08,211 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:08,211 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:08,744 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:08,744 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:09,044 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:09,045 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:09,174 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:09,174 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:09,528 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:09,528 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:09,778 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:09,778 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:09,893 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:09,893 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:10,027 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:10,028 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:10,177 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:10,178 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:10,287 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:10,287 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:10,512 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:10,513 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:10,796 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:10,797 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:10:10,977 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:10:10,978 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:11:31,070 log 7436 3112 Unauthorized: /api/login/
WARNING 2025-03-15 17:11:31,071 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 401 31
WARNING 2025-03-15 17:12:09,261 log 7436 3112 Unsupported Media Type: /api/login/
WARNING 2025-03-15 17:12:09,262 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 415 62
WARNING 2025-03-15 17:13:32,852 log 7436 3112 Unauthorized: /api/login/
WARNING 2025-03-15 17:13:32,853 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 401 31
WARNING 2025-03-15 17:13:35,769 log 7436 3112 Unauthorized: /api/login/
WARNING 2025-03-15 17:13:35,769 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 401 31
WARNING 2025-03-15 17:13:37,259 log 7436 3112 Unauthorized: /api/login/
WARNING 2025-03-15 17:13:37,259 basehttp 7436 3112 "POST /api/login/ HTTP/1.1" 401 31
INFO 2025-03-15 17:13:41,986 basehttp 7436 12200 "GET /admin/password_change/ HTTP/1.1" 200 10454
INFO 2025-03-15 17:13:59,857 basehttp 7436 12200 "POST /admin/password_change/ HTTP/1.1" 200 10647
INFO 2025-03-15 17:18:34,530 autoreload 17436 18536 Watching for file changes with StatReloader
INFO 2025-03-15 17:18:40,354 basehttp 17436 20992 "GET / HTTP/1.1" 200 40
INFO 2025-03-15 17:22:24,685 basehttp 17436 20992 "GET / HTTP/1.1" 200 40
INFO 2025-03-15 17:22:28,996 basehttp 17436 20992 "GET /admin/ HTTP/1.1" 200 10301
WARNING 2025-03-15 17:22:53,895 log 17436 20204 Unauthorized: /api/login/
WARNING 2025-03-15 17:22:53,896 basehttp 17436 20204 "POST /api/login/ HTTP/1.1" 401 31
INFO 2025-03-15 17:23:31,262 basehttp 17436 20204 "POST /api/login/ HTTP/1.1" 200 524
INFO 2025-03-15 21:32:26,766 autoreload 3672 10220 Watching for file changes with StatReloader
INFO 2025-03-15 21:39:14,629 basehttp 3672 10616 "POST /api/login/ HTTP/1.1" 200 524
ERROR 2025-03-15 21:43:11,027 log 3672 10604 Bad Gateway: /api/defects/analyze/
ERROR 2025-03-15 21:43:11,029 basehttp 3672 10604 "POST /api/defects/analyze/ HTTP/1.1" 502 126
INFO 2025-03-15 22:12:21,280 autoreload 3672 10220 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 22:12:22,228 autoreload 11772 16424 Watching for file changes with StatReloader
INFO 2025-03-15 22:39:16,578 autoreload 15088 3000 Watching for file changes with StatReloader
INFO 2025-03-15 22:41:05,350 autoreload 15088 3000 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 22:41:05,975 autoreload 11772 16424 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 22:41:06,394 autoreload 7824 16420 Watching for file changes with StatReloader
INFO 2025-03-15 22:41:06,866 autoreload 9968 14192 Watching for file changes with StatReloader
INFO 2025-03-15 22:45:35,046 autoreload 9968 14192 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 22:45:35,701 autoreload 7824 16420 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-15 22:45:36,200 autoreload 12088 3752 Watching for file changes with StatReloader
INFO 2025-03-15 22:45:36,738 autoreload 9392 12880 Watching for file changes with StatReloader
WARNING 2025-03-15 23:01:27,165 log 12088 7480 Unauthorized: /api/defects/analyze/
WARNING 2025-03-15 23:01:27,167 basehttp 12088 7480 "POST /api/defects/analyze/ HTTP/1.1" 401 172
INFO 2025-03-16 06:02:43,875 basehttp 12088 17284 "POST /api/login/ HTTP/1.1" 200 524
ERROR 2025-03-16 06:07:42,008 log 12088 18240 Bad Gateway: /api/defects/analyze/
ERROR 2025-03-16 06:07:42,011 basehttp 12088 18240 "POST /api/defects/analyze/ HTTP/1.1" 502 126
INFO 2025-03-16 06:21:04,362 autoreload 12088 3752 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\settings.py changed, reloading.
INFO 2025-03-16 06:21:04,377 autoreload 9392 12880 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\garment_inspection\settings.py changed, reloading.
INFO 2025-03-16 06:21:06,005 autoreload 7484 18704 Watching for file changes with StatReloader
INFO 2025-03-16 06:21:27,310 autoreload 7484 18704 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-16 06:21:27,340 autoreload 3960 17740 E:\Github\Garment inpection system\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-03-16 06:21:28,493 autoreload 8308 7148 Watching for file changes with StatReloader
INFO 2025-03-16 06:21:28,496 autoreload 15516 17916 Watching for file changes with StatReloader
INFO 2025-03-16 06:21:54,160 basehttp 15516 4200 "POST /api/login/ HTTP/1.1" 200 524
WARNING 2025-03-16 06:22:41,312 log 15516 4200 Bad Request: /api/defects/analyze/
WARNING 2025-03-16 06:22:41,314 basehttp 15516 4200 "POST /api/defects/analyze/ HTTP/1.1" 400 61
ERROR 2025-03-16 06:24:15,676 views 15516 3648 Error in analyze_defect_image: no such table: inspection_fabricdefect
ERROR 2025-03-16 06:24:15,678 log 15516 3648 Internal Server Error: /api/defects/analyze/
ERROR 2025-03-16 06:24:15,681 basehttp 15516 3648 "POST /api/defects/analyze/ HTTP/1.1" 500 80
WARNING 2025-03-16 11:05:29,067 log 15516 14968 Unauthorized: /api/defects/analyze/
WARNING 2025-03-16 11:05:29,071 basehttp 15516 14968 "POST /api/defects/analyze/ HTTP/1.1" 401 172
INFO 2025-03-16 11:05:41,472 basehttp 15516 14968 "POST /api/login/ HTTP/1.1" 200 524
INFO 2025-03-16 11:06:19,803 basehttp 15516 14968 "POST /api/defects/analyze/ HTTP/1.1" 200 4289
INFO 2025-03-16 11:10:36,100 basehttp 15516 15900 "GET / HTTP/1.1" 200 40
WARNING 2025-03-16 11:10:36,183 log 15516 15900 Not Found: /favicon.ico
WARNING 2025-03-16 11:10:36,183 basehttp 15516 15900 "GET /favicon.ico HTTP/1.1" 404 4958
INFO 2025-03-16 11:10:36,580 basehttp 15516 15900 "GET / HTTP/1.1" 200 40
INFO 2025-03-16 11:10:42,606 basehttp 15516 15900 "GET /admin/ HTTP/1.1" 200 10301
INFO 2025-03-16 11:10:42,621 basehttp 15516 15900 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,621 basehttp 15516 10656 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,622 basehttp 15516 6248 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,628 basehttp 15516 15900 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,628 basehttp 15516 6248 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,628 basehttp 15516 10656 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,631 basehttp 15516 6248 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,638 basehttp 15516 6248 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-03-16 11:10:42,638 basehttp 15516 15900 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,429 basehttp 15516 6248 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 10486
INFO 2025-03-16 11:10:47,448 basehttp 15516 6248 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,456 basehttp 15516 19864 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,456 basehttp 15516 15900 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,457 basehttp 15516 10656 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,462 basehttp 15516 18252 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,462 basehttp 15516 19864 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,464 basehttp 15516 18140 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,464 basehttp 15516 10656 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,464 basehttp 15516 15900 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,471 basehttp 15516 10656 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-03-16 11:10:47,488 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:10:47,503 basehttp 15516 6248 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-03-16 11:10:50,828 basehttp 15516 6248 "GET /admin/inspection/fabricdefect/ HTTP/1.1" 200 12370
INFO 2025-03-16 11:10:50,850 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:10:56,467 basehttp 15516 6248 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10859
INFO 2025-03-16 11:10:56,482 basehttp 15516 10656 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-03-16 11:10:56,484 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:10:59,750 basehttp 15516 6248 "GET /admin/inspection/cliinspector/add/ HTTP/1.1" 200 12504
INFO 2025-03-16 11:10:59,768 basehttp 15516 10656 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:59,772 basehttp 15516 18140 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:10:59,776 basehttp 15516 18140 "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-03-16 11:10:59,842 basehttp 15516 6248 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-03-16 11:10:59,848 basehttp 15516 18140 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-03-16 11:11:03,015 basehttp 15516 18140 "GET /admin/auth/user/add/ HTTP/1.1" 200 15038
INFO 2025-03-16 11:11:03,035 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:03,042 basehttp 15516 18140 "GET /static/admin/css/unusable_password_field.css HTTP/1.1" 200 663
INFO 2025-03-16 11:11:03,057 basehttp 15516 6248 "GET /static/admin/js/unusable_password_field.js HTTP/1.1" 200 1480
INFO 2025-03-16 11:11:05,824 basehttp 15516 6248 "GET /admin/auth/group/ HTTP/1.1" 200 10761
INFO 2025-03-16 11:11:05,839 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:08,150 basehttp 15516 6248 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 10486
INFO 2025-03-16 11:11:08,167 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:09,673 basehttp 15516 6248 "GET /admin/inspection/inspection/ HTTP/1.1" 200 10467
INFO 2025-03-16 11:11:09,692 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:12,081 basehttp 15516 6248 "GET /admin/inspection/supervisor/ HTTP/1.1" 200 10467
INFO 2025-03-16 11:11:12,100 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:13,979 basehttp 15516 6248 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10859
INFO 2025-03-16 11:11:14,001 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:16,515 basehttp 15516 6248 "GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 13133
INFO 2025-03-16 11:11:16,541 basehttp 15516 6248 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2025-03-16 11:11:20,999 basehttp 15516 6248 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 10486
INFO 2025-03-16 11:11:21,022 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:22,539 basehttp 15516 6248 "GET /admin/auth/user/ HTTP/1.1" 200 14833
INFO 2025-03-16 11:11:22,552 basehttp 15516 18140 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2025-03-16 11:11:22,555 basehttp 15516 6248 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:11:22,568 basehttp 15516 6248 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-03-16 11:19:06,897 basehttp 15516 8212 "GET /admin/inspection/cliinspector/add/ HTTP/1.1" 200 12504
INFO 2025-03-16 11:19:06,924 basehttp 15516 8212 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:19:08,695 basehttp 15516 8212 "GET /admin/inspection/inspection/ HTTP/1.1" 200 10467
INFO 2025-03-16 11:19:08,711 basehttp 15516 8212 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:19:09,540 basehttp 15516 8212 "GET /admin/inspection/inspection/ HTTP/1.1" 200 10467
INFO 2025-03-16 11:19:09,562 basehttp 15516 8212 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-16 11:19:12,198 basehttp 15516 8212 "GET /admin/inspection/inspection/add/ HTTP/1.1" 200 18367
INFO 2025-03-16 11:19:12,221 basehttp 15516 8212 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-22 20:47:05,688 autoreload 20620 31120 Watching for file changes with StatReloader
INFO 2025-03-22 20:47:23,272 basehttp 20620 9668 "GET / HTTP/1.1" 200 40
WARNING 2025-03-22 20:47:23,548 log 20620 9668 Not Found: /favicon.ico
WARNING 2025-03-22 20:47:23,550 basehttp 20620 9668 "GET /favicon.ico HTTP/1.1" 404 4958
INFO 2025-03-22 20:48:41,387 basehttp 20620 31696 "GET /admin/login/?next=/login HTTP/1.1" 200 4158
INFO 2025-03-22 20:48:41,992 basehttp 20620 15280 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-03-22 20:48:42,038 basehttp 20620 31696 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-03-22 20:48:42,044 basehttp 20620 27332 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-03-22 20:48:42,044 basehttp 20620 21036 "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-03-22 20:48:42,057 basehttp 20620 11424 "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-03-22 20:48:42,059 basehttp 20620 13280 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-03-22 20:48:42,072 basehttp 20620 13280 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-03-22 20:48:52,395 basehttp 20620 13280 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-03-22 20:48:52,424 basehttp 20620 13280 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
INFO 2025-03-22 20:49:02,629 basehttp 20620 13280 "GET /admin/login/?next=/login HTTP/1.1" 200 4158
INFO 2025-03-23 13:57:54,054 autoreload 12084 1236 Watching for file changes with StatReloader
INFO 2025-03-23 13:57:58,849 basehttp 12084 30452 "GET / HTTP/1.1" 200 40
WARNING 2025-03-23 13:57:59,208 log 12084 30452 Not Found: /favicon.ico
WARNING 2025-03-23 13:57:59,211 basehttp 12084 30452 "GET /favicon.ico HTTP/1.1" 404 4958
INFO 2025-03-23 13:58:06,757 basehttp 12084 30452 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-03-23 13:58:06,909 basehttp 12084 30452 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
INFO 2025-03-23 13:58:06,949 basehttp 12084 30452 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-23 13:58:06,949 basehttp 12084 11920 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-03-23 13:58:06,950 basehttp 12084 12428 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-23 13:58:06,951 basehttp 12084 19072 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-23 13:58:06,952 basehttp 12084 14672 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-23 13:58:06,955 basehttp 12084 33032 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-23 13:58:06,978 basehttp 12084 33032 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-23 13:58:17,602 basehttp 12084 33032 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-03-23 13:58:17,649 basehttp 12084 33032 "GET /admin/ HTTP/1.1" 200 10293
INFO 2025-03-23 13:58:17,920 basehttp 12084 33032 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-03-23 13:58:17,940 basehttp 12084 19072 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-23 13:58:17,945 basehttp 12084 11920 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-03-23 13:58:30,516 basehttp 12084 11920 "GET /admin/inspection/inspection/ HTTP/1.1" 200 10459
INFO 2025-03-23 13:58:30,549 basehttp 12084 11920 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-03-23 13:58:30,551 basehttp 12084 14672 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-03-23 13:58:30,560 basehttp 12084 30452 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-03-23 13:58:30,564 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 13:58:30,569 basehttp 12084 12428 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-03-23 13:58:30,582 basehttp 12084 11920 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-03-23 13:58:30,585 basehttp 12084 14672 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-03-23 13:58:30,589 basehttp 12084 30452 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-03-23 13:58:30,637 basehttp 12084 33032 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-03-23 13:58:30,646 basehttp 12084 19072 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-03-23 13:58:30,688 basehttp 12084 33032 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-03-23 13:58:30,790 basehttp 12084 33032 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-03-23 13:58:34,764 basehttp 12084 33032 "GET /admin/inspection/inspection/add/ HTTP/1.1" 200 18396
INFO 2025-03-23 13:58:34,793 basehttp 12084 33032 "GET /static/admin/css/forms.css HTTP/1.1" 200 8794
INFO 2025-03-23 13:58:34,797 basehttp 12084 30452 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-03-23 13:58:34,803 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 13:58:34,808 basehttp 12084 33032 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
INFO 2025-03-23 13:58:34,818 basehttp 12084 19072 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-03-23 13:58:34,825 basehttp 12084 33032 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-03-23 13:59:25,614 basehttp 12084 33032 "POST /admin/inspection/inspection/add/ HTTP/1.1" 200 18818
INFO 2025-03-23 13:59:25,641 basehttp 12084 33032 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 13:59:28,645 basehttp 12084 33032 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 10478
INFO 2025-03-23 13:59:28,674 basehttp 12084 33032 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 13:59:34,028 basehttp 12084 33032 "GET /admin/auth/group/ HTTP/1.1" 200 10753
INFO 2025-03-23 13:59:34,056 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 13:59:34,068 basehttp 12084 33032 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-03-23 13:59:36,035 basehttp 12084 33032 "GET /admin/auth/user/ HTTP/1.1" 200 15267
INFO 2025-03-23 13:59:36,065 basehttp 12084 33032 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 13:59:36,076 basehttp 12084 19072 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-03-23 13:59:36,113 basehttp 12084 19072 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-03-23 13:59:42,330 basehttp 12084 19072 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 10478
INFO 2025-03-23 13:59:42,383 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 13:59:44,952 basehttp 12084 19072 "GET /admin/inspection/cliinspector/add/ HTTP/1.1" 200 12496
INFO 2025-03-23 13:59:45,063 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:00:28,247 basehttp 12084 19072 "POST /admin/inspection/cliinspector/add/ HTTP/1.1" 302 0
INFO 2025-03-23 14:00:28,280 basehttp 12084 19072 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 12701
INFO 2025-03-23 14:00:28,335 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:00:32,951 basehttp 12084 19072 "GET /admin/inspection/fabricdefect/ HTTP/1.1" 200 12362
INFO 2025-03-23 14:00:32,978 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:00:39,623 basehttp 12084 19072 "GET /admin/inspection/inspection/ HTTP/1.1" 200 10459
INFO 2025-03-23 14:00:39,655 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:00:41,730 basehttp 12084 19072 "GET /admin/inspection/supervisor/ HTTP/1.1" 200 10459
INFO 2025-03-23 14:00:41,756 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:00:43,463 basehttp 12084 19072 "GET /admin/inspection/supervisor/ HTTP/1.1" 200 10459
INFO 2025-03-23 14:00:43,491 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:00:44,327 basehttp 12084 19072 "GET /admin/inspection/supervisor/add/ HTTP/1.1" 200 13124
INFO 2025-03-23 14:00:44,361 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:01:19,236 basehttp 12084 19072 "POST /admin/inspection/supervisor/add/ HTTP/1.1" 302 0
INFO 2025-03-23 14:01:19,268 basehttp 12084 19072 "GET /admin/inspection/supervisor/ HTTP/1.1" 200 12652
INFO 2025-03-23 14:01:19,300 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:01:21,806 basehttp 12084 19072 "GET /admin/inspection/inspection/ HTTP/1.1" 200 10459
INFO 2025-03-23 14:01:21,847 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:01:25,407 basehttp 12084 19072 "GET /admin/inspection/inspection/add/ HTTP/1.1" 200 18466
INFO 2025-03-23 14:01:25,438 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:01:38,110 basehttp 12084 19072 "POST /admin/inspection/inspection/add/ HTTP/1.1" 302 0
INFO 2025-03-23 14:01:38,142 basehttp 12084 19072 "GET /admin/inspection/inspection/ HTTP/1.1" 200 12770
INFO 2025-03-23 14:01:38,352 basehttp 12084 19072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:19:12,618 autoreload 35048 31476 Watching for file changes with StatReloader
INFO 2025-03-23 14:19:16,029 basehttp 35048 17956 "GET / HTTP/1.1" 200 40
INFO 2025-03-23 14:19:20,731 basehttp 35048 17956 "GET /admin/login/?next=/login HTTP/1.1" 302 0
INFO 2025-03-23 14:19:20,780 basehttp 35048 17956 "GET /admin/ HTTP/1.1" 200 11411
INFO 2025-03-23 14:19:23,304 basehttp 35048 17956 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 12489
INFO 2025-03-23 14:19:23,360 basehttp 35048 17956 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:19:26,122 basehttp 35048 17956 "GET /admin/inspection/cliinspector/add/ HTTP/1.1" 200 12496
INFO 2025-03-23 14:19:26,161 basehttp 35048 17956 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 14:44:33,167 autoreload 20956 33152 Watching for file changes with StatReloader
INFO 2025-03-23 14:45:19,980 autoreload 20956 33152 C:\Users\Hassan\Desktop\SDGP_frontend\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-03-23 14:45:21,298 autoreload 11616 36148 Watching for file changes with StatReloader
INFO 2025-03-23 14:51:46,718 basehttp 11616 20764 "GET /admin/ HTTP/1.1" 200 11411
WARNING 2025-03-23 14:53:03,957 log 11616 33336 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 14:53:03,958 basehttp 11616 33336 "GET //api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
INFO 2025-03-23 14:53:04,562 basehttp 11616 34100 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
INFO 2025-03-23 14:53:04,575 basehttp 11616 34100 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
INFO 2025-03-23 14:53:04,585 basehttp 11616 27076 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2025-03-23 14:53:04,600 basehttp 11616 34100 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2025-03-23 14:53:04,601 basehttp 11616 33336 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2025-03-23 14:53:04,624 basehttp 11616 27076 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2025-03-23 14:53:04,625 basehttp 11616 34100 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2025-03-23 14:53:04,628 basehttp 11616 33336 "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
INFO 2025-03-23 14:53:04,650 basehttp 11616 36772 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
INFO 2025-03-23 14:53:04,686 basehttp 11616 26800 "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
INFO 2025-03-23 14:53:04,695 basehttp 11616 35632 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2025-03-23 14:53:04,712 basehttp 11616 35632 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
WARNING 2025-03-23 14:53:45,029 log 11616 32860 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 14:53:45,030 basehttp 11616 32860 "GET //api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
INFO 2025-03-23 14:53:48,021 basehttp 11616 32860 "GET /admin/ HTTP/1.1" 200 11411
INFO 2025-03-23 14:53:51,957 basehttp 11616 32860 "GET /admin/ HTTP/1.1" 200 11411
WARNING 2025-03-23 15:23:46,766 log 11616 35076 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 15:23:46,769 basehttp 11616 35076 "GET //api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
WARNING 2025-03-23 15:23:49,136 log 11616 35076 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 15:23:49,139 basehttp 11616 35076 "GET //api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
WARNING 2025-03-23 15:23:52,945 log 11616 35076 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 15:23:52,947 basehttp 11616 35076 "GET //api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
WARNING 2025-03-23 15:23:55,540 log 11616 35076 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 15:23:55,541 basehttp 11616 35076 "GET //api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
WARNING 2025-03-23 15:24:17,766 log 11616 35076 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 15:24:17,769 basehttp 11616 35076 "GET //api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
INFO 2025-03-23 15:24:20,091 basehttp 11616 35076 "GET /admin/ HTTP/1.1" 200 11411
INFO 2025-03-23 15:24:22,160 basehttp 11616 35076 "GET /admin/auth/user/ HTTP/1.1" 200 15267
INFO 2025-03-23 15:24:22,213 basehttp 11616 35076 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 15:27:42,256 basehttp 11616 35076 "GET /admin/token_blacklist/ HTTP/1.1" 200 6009
INFO 2025-03-23 15:27:44,561 basehttp 11616 35076 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 15:27:44,584 basehttp 11616 35076 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 15:27:48,010 basehttp 11616 35076 "GET /admin/token_blacklist/ HTTP/1.1" 200 6009
INFO 2025-03-23 15:27:49,326 basehttp 11616 35076 "GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 13125
INFO 2025-03-23 15:27:56,651 basehttp 11616 35076 "GET /admin/token_blacklist/ HTTP/1.1" 200 6009
INFO 2025-03-23 16:17:08,327 autoreload 42164 40964 Watching for file changes with StatReloader
INFO 2025-03-23 16:17:14,794 basehttp 42164 42388 "GET / HTTP/1.1" 200 40
WARNING 2025-03-23 16:18:02,488 log 42164 42388 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 16:18:02,490 basehttp 42164 42388 "GET /api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
INFO 2025-03-23 16:31:00,156 autoreload 43584 10252 Watching for file changes with StatReloader
INFO 2025-03-23 16:31:03,449 basehttp 43584 43048 "GET / HTTP/1.1" 200 40
WARNING 2025-03-23 16:31:09,710 log 43584 43048 Method Not Allowed: /login/
WARNING 2025-03-23 16:31:09,714 basehttp 43584 43048 "GET /login/ HTTP/1.1" 405 5549
INFO 2025-03-23 16:31:18,286 basehttp 43584 43048 "GET /admin/ HTTP/1.1" 200 11411
INFO 2025-03-23 16:31:18,326 basehttp 43584 43048 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,329 basehttp 43584 22508 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,336 basehttp 43584 44896 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,349 basehttp 43584 44900 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,354 basehttp 43584 44904 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,358 basehttp 43584 44908 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,364 basehttp 43584 44904 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,373 basehttp 43584 44904 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-03-23 16:31:18,377 basehttp 43584 44908 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,425 basehttp 43584 44908 "GET /admin/auth/user/ HTTP/1.1" 200 15707
INFO 2025-03-23 16:31:29,455 basehttp 43584 44900 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,462 basehttp 43584 44908 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,467 basehttp 43584 43048 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,480 basehttp 43584 44896 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,484 basehttp 43584 22508 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,493 basehttp 43584 44904 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 16:31:29,497 basehttp 43584 44900 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,502 basehttp 43584 44908 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,505 basehttp 43584 43048 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,516 basehttp 43584 44896 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,623 basehttp 43584 43048 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,720 basehttp 43584 44908 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,724 basehttp 43584 44900 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2025-03-23 16:31:29,802 basehttp 43584 44904 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-03-23 16:31:30,188 basehttp 43584 44896 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-03-23 16:31:30,210 basehttp 43584 43048 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
WARNING 2025-03-23 16:31:45,971 log 43584 43048 Unauthorized: /api/inspection_count/
WARNING 2025-03-23 16:31:45,974 basehttp 43584 43048 "GET /api/inspection_count/?date=2025-03-23 HTTP/1.1" 401 5214
INFO 2025-03-23 16:32:05,997 basehttp 43584 43048 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 16:32:06,028 basehttp 43584 43048 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 16:32:12,920 basehttp 43584 43048 "GET /admin/token_blacklist/blacklistedtoken/add/ HTTP/1.1" 200 12519
INFO 2025-03-23 16:32:12,953 basehttp 43584 44896 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 16:32:12,960 basehttp 43584 43048 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-03-23 16:32:12,967 basehttp 43584 44904 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2025-03-23 16:32:12,970 basehttp 43584 44896 "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-03-23 16:32:12,984 basehttp 43584 44904 "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-03-23 17:04:45,215 basehttp 43584 45460 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:04:45,261 basehttp 43584 45460 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:04:47,401 basehttp 43584 45460 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:04:47,430 basehttp 43584 45460 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:04:49,375 basehttp 43584 45460 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:04:49,423 basehttp 43584 45460 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:04:52,756 basehttp 43584 45460 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:04:52,780 basehttp 43584 45460 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:04:54,989 basehttp 43584 45460 "GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 13125
INFO 2025-03-23 17:05:05,794 basehttp 43584 45460 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:05:05,820 basehttp 43584 45460 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:05:15,907 basehttp 43584 45460 "GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 13125
INFO 2025-03-23 17:05:32,283 basehttp 43584 45460 "GET /admin/token_blacklist/outstandingtoken/5/change/ HTTP/1.1" 200 14409
INFO 2025-03-23 17:05:32,308 basehttp 43584 45460 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-03-23 17:06:46,731 log 43584 45460 Not Found: /auth/login
WARNING 2025-03-23 17:06:46,732 basehttp 43584 45460 "GET /auth/login HTTP/1.1" 404 5234
WARNING 2025-03-23 17:07:50,486 log 43584 45460 Method Not Allowed: /login/
WARNING 2025-03-23 17:07:50,488 basehttp 43584 45460 "GET /login/ HTTP/1.1" 405 5549
INFO 2025-03-23 17:07:50,524 basehttp 43584 43744 "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,527 basehttp 43584 45460 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,528 basehttp 43584 39716 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,529 basehttp 43584 47072 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,540 basehttp 43584 33272 "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,550 basehttp 43584 43744 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,556 basehttp 43584 45460 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,558 basehttp 43584 47108 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,568 basehttp 43584 39716 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,574 basehttp 43584 33272 "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,578 basehttp 43584 47072 "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
INFO 2025-03-23 17:07:50,580 basehttp 43584 43744 "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
INFO 2025-03-23 17:08:04,505 basehttp 43584 47072 "GET /admin/login/?next=/login HTTP/1.1" 302 0
INFO 2025-03-23 17:08:04,543 basehttp 43584 47072 "GET /admin/ HTTP/1.1" 200 11411
INFO 2025-03-23 17:08:30,341 basehttp 43584 47072 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:08:30,371 basehttp 43584 47072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:08:39,278 basehttp 43584 47072 "GET /admin/token_blacklist/blacklistedtoken/add/ HTTP/1.1" 200 12519
INFO 2025-03-23 17:08:39,313 basehttp 43584 47072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:09:13,079 basehttp 43584 47072 "GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 13125
INFO 2025-03-23 17:09:33,176 basehttp 43584 47072 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:09:33,201 basehttp 43584 47072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:09:37,553 basehttp 43584 47072 "GET /admin/token_blacklist/blacklistedtoken/add/ HTTP/1.1" 200 12519
INFO 2025-03-23 17:09:37,579 basehttp 43584 47072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:09:51,698 basehttp 43584 47072 "GET /admin/auth/user/ HTTP/1.1" 200 15707
INFO 2025-03-23 17:09:51,735 basehttp 43584 47072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-23 17:14:05,707 basehttp 43584 47072 "GET /admin/token_blacklist/blacklistedtoken/ HTTP/1.1" 200 10851
INFO 2025-03-23 17:14:05,735 basehttp 43584 47072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-03-24 08:58:59,310 autoreload 63128 77820 Watching for file changes with StatReloader
INFO 2025-04-02 14:13:54,897 autoreload 11676 21812 Watching for file changes with StatReloader
INFO 2025-04-02 14:15:38,139 autoreload 11676 21812 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-02 14:15:38,772 autoreload 20784 21036 Watching for file changes with StatReloader
INFO 2025-04-02 14:16:17,875 autoreload 20784 21036 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\permissions.py changed, reloading.
INFO 2025-04-02 14:16:18,465 autoreload 12368 2680 Watching for file changes with StatReloader
INFO 2025-04-02 14:16:53,232 autoreload 7828 11848 Watching for file changes with StatReloader
INFO 2025-04-02 14:17:37,531 autoreload 2500 4736 Watching for file changes with StatReloader
INFO 2025-04-02 14:17:43,022 basehttp 12368 21676 "GET / HTTP/1.1" 200 40
WARNING 2025-04-02 14:17:43,416 log 12368 21676 Not Found: /favicon.ico
WARNING 2025-04-02 14:17:43,417 basehttp 12368 21676 "GET /favicon.ico HTTP/1.1" 404 9189
INFO 2025-04-02 14:17:44,284 basehttp 12368 21676 "GET / HTTP/1.1" 200 40
INFO 2025-04-02 14:17:47,634 basehttp 12368 12276 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-04-02 14:17:47,755 basehttp 12368 12276 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
INFO 2025-04-02 14:17:47,880 basehttp 12368 12276 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-04-02 14:17:50,540 basehttp 12368 12276 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
INFO 2025-04-02 14:17:56,657 basehttp 12368 12276 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4322
INFO 2025-04-02 14:18:36,110 basehttp 12368 12276 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-04-02 14:18:36,145 basehttp 12368 12276 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-02 14:18:42,589 basehttp 12368 12276 "GET /admin/auth/user/ HTTP/1.1" 200 15655
INFO 2025-04-02 14:18:42,636 basehttp 12368 12276 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-02 14:18:42,774 basehttp 12368 12276 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2025-04-02 14:20:17,030 autoreload 7828 11848 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\permissions.py changed, reloading.
INFO 2025-04-02 14:20:17,086 autoreload 12368 2680 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\permissions.py changed, reloading.
INFO 2025-04-02 14:20:17,092 autoreload 2500 4736 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\permissions.py changed, reloading.
INFO 2025-04-02 14:20:17,709 autoreload 21896 22048 Watching for file changes with StatReloader
INFO 2025-04-02 14:20:17,740 autoreload 9720 15616 Watching for file changes with StatReloader
INFO 2025-04-02 14:20:17,758 autoreload 15684 8060 Watching for file changes with StatReloader
WARNING 2025-04-02 14:25:03,757 log 21896 8404 Unauthorized: /api/login/
WARNING 2025-04-02 14:25:03,757 basehttp 21896 8404 "POST /api/login/ HTTP/1.1" 401 31
WARNING 2025-04-02 14:25:22,447 log 21896 8404 Unauthorized: /api/login/
WARNING 2025-04-02 14:25:22,447 basehttp 21896 8404 "POST /api/login/ HTTP/1.1" 401 31
WARNING 2025-04-02 14:25:53,020 log 21896 8404 Unauthorized: /api/login/
WARNING 2025-04-02 14:25:53,021 basehttp 21896 8404 "POST /api/login/ HTTP/1.1" 401 31
INFO 2025-04-02 14:26:17,426 basehttp 21896 8404 "POST /api/login/ HTTP/1.1" 200 524
INFO 2025-04-02 14:41:40,749 autoreload 15684 8060 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:41:40,924 autoreload 9720 15616 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:41:40,985 autoreload 21896 22048 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:41:41,332 autoreload 21424 11292 Watching for file changes with StatReloader
INFO 2025-04-02 14:41:41,510 autoreload 18552 14356 Watching for file changes with StatReloader
INFO 2025-04-02 14:41:41,627 autoreload 18712 18592 Watching for file changes with StatReloader
INFO 2025-04-02 14:41:45,717 autoreload 300 12428 Watching for file changes with StatReloader
INFO 2025-04-02 14:42:10,700 autoreload 3664 11216 Watching for file changes with StatReloader
INFO 2025-04-02 14:44:04,060 autoreload 3664 11216 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:44:04,160 autoreload 300 12428 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:44:04,541 autoreload 18712 18592 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:44:04,547 autoreload 18552 14356 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:44:04,674 autoreload 9116 6984 Watching for file changes with StatReloader
INFO 2025-04-02 14:44:04,767 autoreload 19584 15224 Watching for file changes with StatReloader
INFO 2025-04-02 14:44:04,789 autoreload 21424 11292 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:44:05,218 autoreload 9104 21392 Watching for file changes with StatReloader
INFO 2025-04-02 14:44:05,227 autoreload 13560 1924 Watching for file changes with StatReloader
INFO 2025-04-02 14:44:05,506 autoreload 13336 19536 Watching for file changes with StatReloader
INFO 2025-04-02 14:44:13,866 autoreload 16124 19904 Watching for file changes with StatReloader
INFO 2025-04-02 14:48:52,063 autoreload 19900 14092 Watching for file changes with StatReloader
INFO 2025-04-02 14:50:56,450 autoreload 9116 6984 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:50:56,656 autoreload 16124 19904 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:50:56,695 autoreload 13336 19536 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:50:56,847 autoreload 19900 14092 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:50:56,988 autoreload 9104 21392 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:50:57,047 autoreload 19312 14512 Watching for file changes with StatReloader
INFO 2025-04-02 14:50:57,121 autoreload 13560 1924 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:50:57,315 autoreload 19584 15224 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\urls.py changed, reloading.
INFO 2025-04-02 14:50:57,384 autoreload 16608 8564 Watching for file changes with StatReloader
INFO 2025-04-02 14:50:57,443 autoreload 21732 8292 Watching for file changes with StatReloader
INFO 2025-04-02 14:50:57,671 autoreload 11388 4032 Watching for file changes with StatReloader
INFO 2025-04-02 14:50:57,864 autoreload 14644 20004 Watching for file changes with StatReloader
INFO 2025-04-02 14:50:58,003 autoreload 7724 19832 Watching for file changes with StatReloader
INFO 2025-04-02 14:50:58,140 autoreload 5732 21220 Watching for file changes with StatReloader
INFO 2025-04-02 14:51:04,409 basehttp 19312 18444 "GET / HTTP/1.1" 200 40
INFO 2025-04-02 14:51:07,362 basehttp 19312 18444 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:16:57,849 autoreload 19408 10756 Watching for file changes with StatReloader
INFO 2025-04-07 20:18:18,633 autoreload 20144 21592 Watching for file changes with StatReloader
INFO 2025-04-07 20:18:23,885 autoreload 20144 21592 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:18:24,302 autoreload 19408 10756 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:18:24,626 autoreload 16460 12732 Watching for file changes with StatReloader
INFO 2025-04-07 20:18:24,862 autoreload 7784 21132 Watching for file changes with StatReloader
INFO 2025-04-07 20:19:14,936 autoreload 20960 21840 Watching for file changes with StatReloader
INFO 2025-04-07 20:20:33,736 autoreload 16460 12732 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:20:33,889 autoreload 7784 21132 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:20:33,891 autoreload 20960 21840 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:20:34,366 autoreload 24312 18872 Watching for file changes with StatReloader
INFO 2025-04-07 20:20:34,514 autoreload 9120 7704 Watching for file changes with StatReloader
INFO 2025-04-07 20:20:34,514 autoreload 14832 14792 Watching for file changes with StatReloader
INFO 2025-04-07 20:20:40,202 autoreload 24312 18872 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:20:40,466 autoreload 9120 7704 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:20:40,466 autoreload 14832 14792 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\__init__.py changed, reloading.
INFO 2025-04-07 20:20:40,849 autoreload 9704 14448 Watching for file changes with StatReloader
INFO 2025-04-07 20:20:41,116 autoreload 16516 13888 Watching for file changes with StatReloader
INFO 2025-04-07 20:20:59,257 autoreload 19992 15968 Watching for file changes with StatReloader
INFO 2025-04-07 20:22:42,500 autoreload 9704 14448 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:22:43,052 autoreload 21976 20460 Watching for file changes with StatReloader
INFO 2025-04-07 20:22:43,072 autoreload 23528 3688 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:22:43,429 autoreload 16516 13888 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:22:43,457 autoreload 19992 15968 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:22:43,924 autoreload 14668 22596 Watching for file changes with StatReloader
INFO 2025-04-07 20:22:44,260 autoreload 24020 11704 Watching for file changes with StatReloader
INFO 2025-04-07 20:22:44,287 autoreload 21324 11960 Watching for file changes with StatReloader
INFO 2025-04-07 20:23:07,154 autoreload 3848 18532 Watching for file changes with StatReloader
INFO 2025-04-07 20:26:22,344 autoreload 14288 24096 Watching for file changes with StatReloader
INFO 2025-04-07 20:26:58,241 autoreload 21324 11960 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:26:58,243 autoreload 21976 20460 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:26:58,256 autoreload 24020 11704 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:26:58,338 autoreload 14288 24096 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:26:58,417 autoreload 14668 22596 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:26:58,695 autoreload 3848 18532 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:26:59,019 autoreload 23424 2204 Watching for file changes with StatReloader
INFO 2025-04-07 20:26:59,019 autoreload 12772 11464 Watching for file changes with StatReloader
INFO 2025-04-07 20:26:59,023 autoreload 18868 1220 Watching for file changes with StatReloader
INFO 2025-04-07 20:26:59,116 autoreload 6508 7240 Watching for file changes with StatReloader
INFO 2025-04-07 20:26:59,197 autoreload 23544 12468 Watching for file changes with StatReloader
INFO 2025-04-07 20:26:59,425 autoreload 14740 22560 Watching for file changes with StatReloader
INFO 2025-04-07 20:27:10,995 autoreload 22052 10428 Watching for file changes with StatReloader
INFO 2025-04-07 20:27:17,785 basehttp 23424 12328 "GET / HTTP/1.1" 200 40
WARNING 2025-04-07 20:27:18,240 log 23424 12328 Not Found: /favicon.ico
WARNING 2025-04-07 20:27:18,241 basehttp 23424 12328 "GET /favicon.ico HTTP/1.1" 404 9737
INFO 2025-04-07 20:27:18,520 basehttp 23424 12328 "GET / HTTP/1.1" 200 40
INFO 2025-04-07 20:27:23,558 basehttp 23424 9596 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:27:23,721 basehttp 23424 18516 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,721 basehttp 23424 9596 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,721 basehttp 23424 10520 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,722 basehttp 23424 16024 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,722 basehttp 23424 19472 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,723 basehttp 23424 13624 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,751 basehttp 23424 13624 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,757 basehttp 23424 19472 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-04-07 20:27:23,757 basehttp 23424 13624 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,147 basehttp 23424 13624 "GET /admin/inspection/fabricdefect/ HTTP/1.1" 200 11815
INFO 2025-04-07 20:27:27,171 basehttp 23424 16024 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,171 basehttp 23424 18516 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,171 basehttp 23424 13624 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,171 basehttp 23424 10520 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,172 basehttp 23424 9596 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,174 basehttp 23424 16024 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,174 basehttp 23424 18516 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,175 basehttp 23424 13624 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,175 basehttp 23424 10520 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,192 basehttp 23424 19472 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:27:27,290 basehttp 23424 19472 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:27,311 basehttp 23424 19472 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-04-07 20:27:30,406 basehttp 23424 19472 "GET /admin/inspection/fabricdefect/add/ HTTP/1.1" 200 14381
INFO 2025-04-07 20:27:30,425 basehttp 23424 19472 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:30,425 basehttp 23424 13624 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:30,427 basehttp 23424 10520 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:27:30,429 basehttp 23424 10520 "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-04-07 20:27:30,430 basehttp 23424 13624 "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-04-07 20:27:34,308 basehttp 23424 13624 "GET /admin/inspection/fabricdefect/ HTTP/1.1" 200 11815
INFO 2025-04-07 20:27:35,057 basehttp 23424 13624 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:27:37,985 basehttp 23424 13624 "GET /admin/inspection/inspection/ HTTP/1.1" 200 11796
INFO 2025-04-07 20:27:38,004 basehttp 23424 13624 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:27:40,034 basehttp 23424 13624 "GET /admin/inspection/inspection/add/ HTTP/1.1" 200 19599
INFO 2025-04-07 20:27:40,051 basehttp 23424 10520 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-04-07 20:27:40,053 basehttp 23424 13624 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:27:55,141 basehttp 23424 13624 "GET /admin/inspection/inspection/ HTTP/1.1" 200 11796
INFO 2025-04-07 20:27:55,715 basehttp 23424 13624 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:28:04,402 basehttp 23424 13624 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 11815
INFO 2025-04-07 20:28:04,423 basehttp 23424 13624 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:28:06,120 basehttp 23424 13624 "GET /admin/inspection/cliinspector/add/ HTTP/1.1" 200 13833
INFO 2025-04-07 20:28:06,139 basehttp 23424 13624 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:28:09,169 basehttp 23424 13624 "GET /admin/inspection/cliinspector/ HTTP/1.1" 200 11815
INFO 2025-04-07 20:28:09,842 basehttp 23424 13624 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:28:11,688 basehttp 23424 13624 "GET /admin/inspection/inspection/ HTTP/1.1" 200 11796
INFO 2025-04-07 20:28:11,707 basehttp 23424 13624 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:28:13,099 basehttp 23424 13624 "GET /admin/inspection/inspection/add/ HTTP/1.1" 200 19599
INFO 2025-04-07 20:28:13,124 basehttp 23424 13624 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:28:24,433 basehttp 23424 13624 "GET /admin/inspection/inspection/ HTTP/1.1" 200 11796
INFO 2025-04-07 20:28:26,139 basehttp 23424 3700 "GET /admin/ HTTP/1.1" 200 12179
ERROR 2025-04-07 20:28:30,633 log 23424 3700 Internal Server Error: /admin/inspection/notification/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_notification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_notification
ERROR 2025-04-07 20:28:30,643 basehttp 23424 3700 "GET /admin/inspection/notification/ HTTP/1.1" 500 203324
INFO 2025-04-07 20:28:36,640 basehttp 23424 3700 "GET /admin/ HTTP/1.1" 200 12179
ERROR 2025-04-07 20:28:38,743 log 23424 3700 Internal Server Error: /admin/inspection/operator/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_operator

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_operator
ERROR 2025-04-07 20:28:38,749 basehttp 23424 3700 "GET /admin/inspection/operator/ HTTP/1.1" 500 202772
INFO 2025-04-07 20:28:44,549 basehttp 23424 3700 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:28:46,306 basehttp 23424 3700 "GET /admin/inspection/supervisor/ HTTP/1.1" 200 11796
INFO 2025-04-07 20:28:46,325 basehttp 23424 3700 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:28:48,156 basehttp 23424 3700 "GET /admin/inspection/supervisor/add/ HTTP/1.1" 200 14461
INFO 2025-04-07 20:28:48,174 basehttp 23424 3700 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:28:50,156 basehttp 23424 3700 "GET /admin/inspection/supervisor/ HTTP/1.1" 200 11796
INFO 2025-04-07 20:28:50,368 basehttp 23424 3700 "GET /admin/ HTTP/1.1" 200 12179
ERROR 2025-04-07 20:28:58,873 log 23424 3700 Internal Server Error: /admin/inspection/notification/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_notification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_notification
ERROR 2025-04-07 20:28:58,880 basehttp 23424 3700 "GET /admin/inspection/notification/ HTTP/1.1" 500 203324
INFO 2025-04-07 20:29:00,541 basehttp 23424 3700 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:30:59,418 autoreload 18444 14920 Watching for file changes with StatReloader
INFO 2025-04-07 20:32:06,230 autoreload 5860 20924 Watching for file changes with StatReloader
INFO 2025-04-07 20:43:40,174 autoreload 11436 22268 Watching for file changes with StatReloader
INFO 2025-04-07 20:50:08,141 autoreload 11436 22268 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:50:08,679 autoreload 11532 1668 Watching for file changes with StatReloader
INFO 2025-04-07 20:50:08,737 autoreload 5860 20924 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:50:09,284 autoreload 17616 4068 Watching for file changes with StatReloader
INFO 2025-04-07 20:51:41,447 autoreload 17616 4068 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:51:41,920 autoreload 11532 1668 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:51:41,978 autoreload 8236 13796 Watching for file changes with StatReloader
INFO 2025-04-07 20:51:42,486 autoreload 14792 6736 Watching for file changes with StatReloader
INFO 2025-04-07 20:51:43,701 autoreload 8236 13796 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:51:44,155 autoreload 14792 6736 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:51:44,271 autoreload 12832 10184 Watching for file changes with StatReloader
INFO 2025-04-07 20:51:44,746 autoreload 11164 16356 Watching for file changes with StatReloader
INFO 2025-04-07 20:51:48,711 basehttp 12832 10072 "GET / HTTP/1.1" 200 40
INFO 2025-04-07 20:51:52,467 basehttp 12832 10072 "GET /admin/ HTTP/1.1" 200 12179
ERROR 2025-04-07 20:51:54,887 log 12832 10072 Internal Server Error: /admin/inspection/flag/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_flag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_flag
ERROR 2025-04-07 20:51:54,897 basehttp 12832 10072 "GET /admin/inspection/flag/ HTTP/1.1" 500 202813
INFO 2025-04-07 20:52:01,189 basehttp 12832 10072 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:52:03,418 basehttp 12832 10072 "GET /admin/inspection/inspection/ HTTP/1.1" 200 11796
INFO 2025-04-07 20:52:03,439 basehttp 12832 10072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:52:05,287 basehttp 12832 10072 "GET /admin/inspection/inspection/add/ HTTP/1.1" 200 19599
INFO 2025-04-07 20:52:05,307 basehttp 12832 10072 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:53:35,915 autoreload 12832 10184 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:53:36,041 autoreload 11164 16356 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:53:36,523 autoreload 4804 15744 Watching for file changes with StatReloader
INFO 2025-04-07 20:53:36,626 autoreload 7076 14644 Watching for file changes with StatReloader
INFO 2025-04-07 20:54:29,244 autoreload 24512 14320 Watching for file changes with StatReloader
INFO 2025-04-07 20:56:11,844 autoreload 24512 14320 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:56:12,374 autoreload 12368 13300 Watching for file changes with StatReloader
INFO 2025-04-07 20:56:12,482 autoreload 4804 15744 C:\Programming\Cloned Shii\Final\Automated-7-0-Inspection-System\backend\garment_inspection\inspection\views.py changed, reloading.
INFO 2025-04-07 20:56:13,025 autoreload 11376 1600 Watching for file changes with StatReloader
INFO 2025-04-07 20:56:28,540 basehttp 12368 6184 "GET / HTTP/1.1" 200 40
INFO 2025-04-07 20:56:32,201 basehttp 12368 6184 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 20:56:34,376 basehttp 12368 6184 "GET /admin/inspection/fabricdefect/ HTTP/1.1" 200 11815
INFO 2025-04-07 20:56:34,403 basehttp 12368 6184 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:56:35,598 basehttp 12368 6184 "GET /admin/inspection/fabricdefect/add/ HTTP/1.1" 200 14381
INFO 2025-04-07 20:56:35,618 basehttp 12368 6184 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 20:56:38,379 basehttp 12368 6184 "GET /admin/inspection/fabricdefect/ HTTP/1.1" 200 11815
INFO 2025-04-07 20:56:38,989 basehttp 12368 6184 "GET /admin/ HTTP/1.1" 200 12179
ERROR 2025-04-07 20:56:40,784 log 12368 6184 Internal Server Error: /admin/inspection/flag/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_flag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_flag
ERROR 2025-04-07 20:56:40,793 basehttp 12368 6184 "GET /admin/inspection/flag/ HTTP/1.1" 500 202813
INFO 2025-04-07 20:56:55,698 basehttp 12368 6184 "GET /admin/ HTTP/1.1" 200 12179
ERROR 2025-04-07 20:57:38,705 log 12368 6184 Internal Server Error: /admin/inspection/flag/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_flag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_flag
ERROR 2025-04-07 20:57:38,712 basehttp 12368 6184 "GET /admin/inspection/flag/ HTTP/1.1" 500 202813
INFO 2025-04-07 20:58:36,633 basehttp 12368 6184 "GET /admin/ HTTP/1.1" 200 12179
ERROR 2025-04-07 20:58:41,359 log 12368 6184 Internal Server Error: /admin/inspection/operator/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: inspection_operator

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: inspection_operator
ERROR 2025-04-07 20:58:41,365 basehttp 12368 6184 "GET /admin/inspection/operator/ HTTP/1.1" 500 202564
INFO 2025-04-07 21:00:20,505 autoreload 13452 20176 Watching for file changes with StatReloader
INFO 2025-04-07 21:00:22,956 basehttp 12368 6184 "GET / HTTP/1.1" 200 40
INFO 2025-04-07 21:00:25,992 basehttp 12368 6184 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 21:00:29,371 basehttp 12368 6184 "GET /admin/inspection/flag/ HTTP/1.1" 200 14013
INFO 2025-04-07 21:00:29,400 basehttp 12368 6184 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 21:00:29,500 basehttp 12368 14356 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-04-07 21:00:32,439 basehttp 12368 14356 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 21:00:34,229 basehttp 12368 14356 "GET /admin/inspection/notification/ HTTP/1.1" 200 13261
INFO 2025-04-07 21:00:34,249 basehttp 12368 14356 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 21:00:36,500 basehttp 12368 14356 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 21:00:38,021 basehttp 12368 14356 "GET /admin/inspection/inspection/ HTTP/1.1" 200 11796
INFO 2025-04-07 21:00:38,041 basehttp 12368 14356 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 21:00:39,729 basehttp 12368 14356 "GET /admin/inspection/inspection/add/ HTTP/1.1" 200 19599
INFO 2025-04-07 21:00:39,749 basehttp 12368 14356 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 21:00:41,727 basehttp 12368 14356 "GET /admin/inspection/inspection/ HTTP/1.1" 200 11796
INFO 2025-04-07 21:00:41,947 basehttp 12368 14356 "GET /admin/ HTTP/1.1" 200 12179
INFO 2025-04-07 21:00:43,922 basehttp 12368 14356 "GET /admin/inspection/flag/ HTTP/1.1" 200 14013
INFO 2025-04-07 21:00:43,941 basehttp 12368 14356 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 21:00:47,196 basehttp 12368 14356 "GET /admin/inspection/flag/add/ HTTP/1.1" 200 23288
INFO 2025-04-07 21:00:47,216 basehttp 12368 6184 "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2025-04-07 21:00:47,216 basehttp 12368 172 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2025-04-07 21:00:47,218 basehttp 12368 14356 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-04-07 21:00:47,256 basehttp 12368 14356 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2025-04-07 21:00:47,256 basehttp 12368 172 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2025-04-07 21:00:50,582 basehttp 12368 172 "GET /admin/inspection/flag/ HTTP/1.1" 200 14013
INFO 2025-04-07 21:00:50,802 basehttp 12368 172 "GET /admin/ HTTP/1.1" 200 12179
